CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  transaction_id VARCHAR(64) NOT NULL UNIQUE,
  customer_id VARCHAR(64) NOT NULL,
  customer_name VARCHAR(255),
  email VARCHAR(255),
  phone_number VARCHAR(50),
  amount DECIMAL(18, 2) NOT NULL,
  currency VARCHAR(10),
  transaction_type VARCHAR(50),
  transaction_channel VARCHAR(50),
  transaction_time DATETIME NOT NULL,
  hour_of_day INT,
  day_of_week INT,
  account_age_days INT,
  kyc_status VARCHAR(30),
  customer_risk_level VARCHAR(20),
  merchant_id VARCHAR(64),
  merchant_category VARCHAR(100),
  merchant_country VARCHAR(80),
  merchant_risk_level VARCHAR(20),
  device_id VARCHAR(64),
  device_type VARCHAR(50),
  device_os VARCHAR(50),
  is_new_device BOOLEAN,
  device_change_count_24h INT,
  ip_address VARCHAR(64),
  ip_country VARCHAR(80),
  ip_city VARCHAR(100),
  is_vpn BOOLEAN,
  is_proxy BOOLEAN,
  ip_risk_score DECIMAL(5, 2),
  source_country VARCHAR(80),
  destination_country VARCHAR(80),
  is_cross_border BOOLEAN,
  avg_transaction_amount_30d DECIMAL(18, 2),
  transaction_count_1h INT,
  transaction_count_24h INT,
  failed_login_count_24h INT,
  password_change_recently BOOLEAN,
  beneficiary_is_new BOOLEAN,
  beneficiary_age_days INT,
  distance_from_last_location_km DECIMAL(12, 2),
  minutes_since_last_transaction INT,
  days_since_last_transaction INT,
  is_fraud BOOLEAN,
  fraud_type VARCHAR(80),
  fraud_score DECIMAL(6, 4),
  prediction_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  predicted_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_transactions_prediction_status (prediction_status),
  INDEX idx_transactions_created_at (created_at)
);

